[package]
name = "jira-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clearscreen = "3.0.0"
ellipse = "0.2.0"
itertools = "0.13.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"

[dev-dependencies]
tempfile = "3.10.1"
